language: python

sudo: false
env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-django111-drf31
    - TOX_ENV=py27-django111-drf32
    - TOX_ENV=py27-django111-drf33
    - TOX_ENV=py27-django111-drf34
    - TOX_ENV=py27-django111-drf35
    - TOX_ENV=py27-django111-drf36
    - TOX_ENV=py27-django111-drf37
    - TOX_ENV=py27-django111-drf38
    - TOX_ENV=py34-django111-drf31
    - TOX_ENV=py34-django111-drf32
    - TOX_ENV=py34-django111-drf33
    - TOX_ENV=py34-django111-drf34
    - TOX_ENV=py34-django111-drf35
    - TOX_ENV=py34-django111-drf36
    - TOX_ENV=py34-django111-drf37
    - TOX_ENV=py34-django111-drf38
    - TOX_ENV=py35-django111-drf31
    - TOX_ENV=py35-django111-drf32
    - TOX_ENV=py35-django111-drf33
    - TOX_ENV=py35-django111-drf34
    - TOX_ENV=py35-django111-drf35
    - TOX_ENV=py35-django111-drf36
    - TOX_ENV=py35-django111-drf37
    - TOX_ENV=py35-django111-drf38
    - TOX_ENV=py36-django111-drf31
    - TOX_ENV=py36-django111-drf32
    - TOX_ENV=py36-django111-drf33
    - TOX_ENV=py36-django111-drf34
    - TOX_ENV=py36-django111-drf35
    - TOX_ENV=py36-django111-drf36
    - TOX_ENV=py36-django111-drf37
    - TOX_ENV=py36-django111-drf38
    - TOX_ENV=py34-django20-drf37
    - TOX_ENV=py34-django20-drf38
    - TOX_ENV=py35-django20-drf37
    - TOX_ENV=py35-django20-drf38
    - TOX_ENV=py36-django20-drf37
    - TOX_ENV=py36-django20-drf38
    - TOX_ENV=py37-django20-drf37
    - TOX_ENV=py37-django20-drf38
    - TOX_ENV=py35-django21-drf37
    - TOX_ENV=py35-django21-drf38
    - TOX_ENV=py36-django21-drf37
    - TOX_ENV=py36-django21-drf38
    - TOX_ENV=py37-django21-drf37
    - TOX_ENV=py37-django21-drf38

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
